{
 "title": "Otus Dashboard API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "  histogram_quantile(1, sum by(le, endpoint) (rate(http_response_duration_seconds_bucket{endpoint=~'/api/.*'}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "  histogram_quantile(0.99, sum by(le, endpoint) (rate(http_response_duration_seconds_bucket{endpoint=~'/api/.*'}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "  histogram_quantile(0.95, sum by(le, endpoint) (rate(http_response_duration_seconds_bucket{endpoint=~'/api/.*'}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.5 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "  histogram_quantile(0.5, sum by(le, endpoint) (rate(http_response_duration_seconds_bucket{endpoint=~'/api/.*'}[2m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (endpoint) (increase(http_requests_total{endpoint=~'/api/.*', status=~\"5.+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total{endpoint=~'/api/.*'}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}