{
 "title": "Nginx-Controller",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NGINX Latency MAX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, endpoint) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))"
    }
   ]
  },
  {
   "title": "NGINX Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))"
    }
   ]
  },
  {
   "title": "NGINX Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, endpoint) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))"
    }
   ]
  },
  {
   "title": "NGINX Latency 0.5",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, endpoint) (rate(nginx_ingress_controller_response_duration_seconds_bucket[2m])))"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (endpoint) (increase(nginx_ingress_controller_requests{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "NGINX RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (endpoint)(rate(nginx_ingress_controller_requests[2m]))"
    }
   ]
  }
 ]
}