apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "this.fullname" . }}-dp
  labels:
    app: {{ include "this.fullname" . }}-dp
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "this.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "this.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:

      containers:
        - name: {{ include "this.fullname" . }}-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deployment.port }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "this.fullname" . }}-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "this.fullname" . }}-config
                  key: DATABASE_PORT
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "this.fullname" . }}-config
                  key: DATABASE_USER
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "this.fullname" . }}-config
                  key: DATABASE_NAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "this.fullname" . }}-secret
                  key: DATABASE_PASSWORD

            # Формируем строку подключения к базе данных в переменной окружения database_url.
            - name: PG_URL
              value: postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)?sslmode=disable