apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otus-monitor-nginx
  labels:
    app: otus-monitor-nginx
    release: prometheus
spec:
  endpoints:
    - port: metrics
      scrapeTimeout: 30s
      path: /metrics
      honorLabels: true
      #scheme: http
  #  jobLabel: stack
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller