apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
      protocol: TCP
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
